### ISSUE TITLE
Some questions please

### ISSUE THREAD

**Issue by TheDarkKnight2022** [Sentient111/Csgo-Full-kernel#2]
I am a freshman in Computer Science, I want to make my own hack like you did, but I dont know where to start to learn.  Could you guide me a path of coding cheat? I'll appreciated if you can guide me! :-)

**Comment by Sentient111** [comment]
I personally started with a simple csgo external from usermode (there is a lot of tutorials about that on youtube). Then I got myself the windows internals books and just goofed around on unknowncheats for a while. My best advice is to just start working on something. Don't wait till you found the right tools or the right tutorial or whatever. just start making shit.
