### ISSUE TITLE
bypass

### ISSUE THREAD

**Issue by L1berat1on** [Sentient111/Csgo-Full-kernel#3]
Can't bypass anti cheating in kernel mode

**Comment by L1berat1on** [comment]
Anti cheating of some game platforms runs in kernel mode and may detect calls

**Comment by Sentient111** [comment]
I have no idea what you are trying to tell me. I assume you mean third party anticheats like esporal or faceit? csgo itself only has vac which is usermode only. and for anticheats like faceit kdmapper is the biggest issue.
