### ISSUE TITLE
Issue with pid

### ISSUE THREAD

**Issue by KaroqDave** [Sentient111/Csgo-Full-kernel#5]
Im currently facing some issues regarding the building of the driver itself.
![Errors im getting](https://user-images.githubusercontent.com/47065562/184046672-42979128-3630-4b01-bad2-d521f00e66f9.png)
i cant find a way to fix it, so im asking for help here... maybe u can help me.
kind regards, jay.

**Comment by KaroqDave** [comment]
After couple things ive tried, it seems that ive fixed the issue, but it seems like i got the next one...
![image](https://user-images.githubusercontent.com/47065562/184051794-d5f14b2f-fe79-4e2c-9bd3-ae904a875413.png)
it just constantly says that and doesnt function. at first it gets the correct pid tho.

**Comment by L1berat1on** [comment]
将Classg改为
Class=Processor ; TODO: edit Class
ClassGuid={50127dc3-0f36-415e-a6cc-4cb3be910b65} ; TODO: edit ClassGuid

删除
[ClassInstall32]
Addreg=SampleClassReg
