### ISSUE TITLE
hello, need help to compile, I am learning

### ISSUE THREAD

**Issue by miguellealperez** [Sentient111/Csgo-Full-kernel#7]
hello my name is miguel, I was trying to compile driver by my self, its my first time doing this, I researched and browse that it should be compiled in Debug|x64 My systema architecture is x64, I include the WDK directory to missing files, and at all getting this errors. I aprecite if you let me know what I am doing bad. Just the no target architecture not defined is the principal error.
![image](https://user-images.githubusercontent.com/112134240/187544992-4ab7e30c-0edd-4067-ba52-54a0c455545e.png)

**Comment by miguellealperez** [comment]
Update: Solved installing MVS 2019, and WDK older.

**Comment by s1lence16** [comment]
i need help i get the same error can you help me? Discord: señorita#2500

**Comment by s1lence16** [comment]
> Update: Solved installing MVS 2019, and WDK older.

i need help i get the same error can you help me? Discord: señorita#2500
